algoritmo "semnome"
// Função :
// Autor :
// Data : 29/11/2025
// Seção de Declarações 
var
  largura: real
   comprimento: real
   area: real
inicio
// Seção de Comandos //Entrada
   escreva ("Digite a largura: ")
   leia (largura)

   escreva ("Digite o comprimento: ")
   leia (comprimento)

   //Processamento
   area <- largura * comprimento

   //Saída
   escreva ("O valor da área do terreno é: ", area)
fimalgoritmo

