algoritmo "semnome"
// Função :
// Autor :
// Data : 29/11/2025
// Seção de Declarações 
var
n1: real
n2: real
n3: real
n4: real
perimetro: real
inicio
// Seção de Comandos
//Entradas
escreva ("digite o valor de n1")
leia (n1)

escreva ("digite o valor de n2")
leia (n2)

escreva ("digite o valor de n3")
leia (n3)

escreva ("digite o valor de n4")
leia (n4)

//processamento
perimetro <- (n1 + n2 + n3 + n4)

//saida
escreva ("o perimetro do quadrado é:", perimetro)
fimalgoritmo
