algoritmo "comparacao_preco"
// Função :
// Autor :
// Data : 05/12/2025
// Seção de Declarações 
var
preco1: real
preco2: real

inicio
// Seção de Comandos 
escreva("Digite o primeiro preço: ")
leia(preco1)

escreva("Digite o segundo preço: ")
leia(preco2)

   se (preco1 > preco2) entao
        escreval("O maior preço é: ", preco1)
   senao
        escreval("O maior preço é: ", preco2)
   fimse
fimalgoritmo
