algoritmo "conversao de reais para dolar"
// Função :
// Autor :
// Data : 29/11/2025
// Seção de Declarações 
var
reais: real
dolar: real
cotacao: real

inicio
// Seção de Comandos 
//entradas
escreva ("digite o valor em reais")
leia (reais)

escreva ("digite a cotação do dolar")
leia (cotacao)

//processamento
dolar <- (reais / cotacao)

//saida
escreva ("o valor em dolar é de:", dolar)
fimalgoritmo
