algoritmo "semnome"
// Função :
// Autor :
// Data : 29/11/2025
// Seção de Declarações 
var
idade: inteiro
ano: inteiro
dias: inteiro
inicio
// Seção de Comandos 
//entradas
escreva ("digite a idade do animal")
leia (idade)

escreva ("digite quantos dias equivale um ano")
leia (ano)

//processamento
dias <- (idade*ano)

//saida
escreva ("a idade do animal em dias é de:", dias)
fimalgoritmo
